Use LOMAAAAAAAAAAAA;
INSERT INTO PRODUCTOS( ID_PRODUCTO, DESCRIPCION, PRECIO, STOCK)
  VALUES ( '1' , 'CEMENTO' , '250' , '500' );
INSERT INTO PRODUCTOS( ID_PRODUCTO, DESCRIPCION, PRECIO, STOCK)
  VALUES ( '2' , 'ARENA' , '120' , '1500' );
INSERT INTO PRODUCTOS( ID_PRODUCTO, DESCRIPCION, PRECIO, STOCK)
  VALUES ( '3' , 'CAL' , '90' , '250' );
INSERT INTO PRODUCTOS( ID_PRODUCTO, DESCRIPCION, PRECIO, STOCK)
  VALUES ( '4' , 'PIEDRA' , '120' , '800' );